<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241127162420 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE client (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            last_name VARCHAR(255) NOT NULL, 
            first_name VARCHAR(255) NOT NULL, 
            age INT NOT NULL, 
            fico_score INT NOT NULL, 
            income INT NOT NULL, 
            email VARCHAR(255) NOT NULL, 
            phone_number VARCHAR(255) NOT NULL, 
            ssn VARCHAR(255) NOT NULL, 
            address VARCHAR(255) NOT NULL, 
            city VARCHAR(255) NOT NULL, 
            state VARCHAR(2) NOT NULL, 
            zip VARCHAR(5) NOT NULL, 
            PRIMARY KEY(id))
            ');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE clients');
    }
}
