<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241128133844 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE credit (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
            product_name VARCHAR(255) NOT NULL, 
            end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, 
            percent_rate NUMERIC(5, 3) NOT NULL, 
            credit_sum INT NOT NULL, 
            client_id INT NOT NULL, 
            PRIMARY KEY(id))
        ');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1CC16EFE19EB6921 ON credit (client_id)');
        $this->addSql('ALTER TABLE credit ADD CONSTRAINT FK_1CC16EFE19EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE credit DROP CONSTRAINT FK_1CC16EFE19EB6921');
        $this->addSql('DROP TABLE credit');
    }
}
